/** Новые предметы и черты NPC, встречающиеся только в Voll Adventures. */
export const VOLL_ITEMS = {
  "Master Crafter Power Sword": { name: "Силовой меч работы мастера" },
  "Vox Bead": { name: "Вокс-бусина" },
  "Kickback Shotgun": { name: "Дробовик «Отдача»" },
  "Master Crafted Armoured Bodyglove covered by protective clothing": { name: "Бронекомбинезон работы мастера под защитной одеждой" },
  "Ornemental Chrono": { name: "Украшенный хрон" },
  "Ornemental Rebreather": { name: "Украшенный респиратор" },
  "Robes": { name: "Робы" },
  "Chaos Stave": { name: "Посох Хаоса" },
  "Ornate Robes": { name: "Богато украшенные робы" },
  "Holy Symbol": { name: "Священный символ" },
  "Mono-Knife": { name: "Мономолекулярный нож" },
  "Flak Armour": { name: "Флак-броня" },
  "Master Crafted Armoured Bodysuit": { name: "Бронекостюм работы мастера" },
  "Mesh Armour": { name: "Ячеистая броня" },
  "Augmetic Leg (Left Leg)": { name: "Аугметическая нога (левая)" },
  "Auspex": { name: "Ауспик" },
  "Armoured Robes": { name: "Бронированные робы" },
  "Skitarii Knife": { name: "Нож скитария" },
  "Large Burnt Robes": { name: "Большие обгоревшие робы" },
  "Various trophies from past kills: scraps of clothing, shoddy jewellery, and a broken Herdcrafted Cleaver handle": { name: "Разные трофеи с былых жертв: клочки одежды, дрянные украшения и сломанная рукоять тесака стада" },
  "45 solars": { name: "45 соляров" },
  "Call for Backup": { name: "Вызвать подкрепление", description: '<p>Находясь в @UUID[Compendium.apex-imperialis.navis-voll-journals.JournalEntry.0sTvCVRuh5Wpawt9.JournalEntryPage.eiMwmm7AQZLlFOkn#f.-the-float]{Поплавке}, Трейс может действием вызвать подкрепление по своей вокс-бусине. Этот призыв слышат все Налётчики в пределах 1 мили. Подкрепление обычно прибывает через [[/r 1d5]] раундов и состоит из @UUID[Compendium.apex-imperialis.navis-core-actors.Actor.ZUWBWGM4eH7xFZ8P]{отбросов} и @UUID[Compendium.apex-imperialis.navis-core-actors.Actor.bB0rMr6Gez3M9bME]{гангеров}.</p>' },
  "Marauder Commander": { name: "Командир налётчиков", description: '<p>Трейс может действием совершить <strong>среднюю (+0) проверку Командования (Лидерство)</strong>. За каждый КУ один из Налётчиков Трейс на средней дистанции может потратить реакцию, чтобы немедленно совершить действие.</p>' },
  "I Know My Ride": { name: "Я знаю свою машину", description: '<p>Рестакс получает Преимущество во всех проверках Пилотирования за рулём своего «Карго-8», включая проверки Техники для его ремонта и обслуживания.</p>' },
  "Wrench (Improvised Weapon)": { name: "Гаечный ключ (подручное оружие)" },
  "Toolkit": { name: "Набор инструментов" },
  "Fearless": { name: "Бесстрашие", description: '<p>Предвестник невосприимчив к состоянию <em>Страх</em>.</p>' },
  "Two-handed Reaper": { name: "Двуручный жнец", description: '<p>Предвестник наловчился водить силовой косой широкими сокрушительными дугами. В его руках оружие получает свойство <em>Разлёт</em>, но его атаки никогда не выбирают целью его самого. Если под лезвие попадут союзники — что ж, на то воля Императора.</p>' },
  "Harbinger's Power Scythe": { name: "Силовая коса Предвестника" },
  "Slippery Burrower": { name: "Скользкий землерой", description: '<p>На мелководье или мягкой земле Ацинади Бета-3 может действием «Спрятаться» зарыться и скрыться из виду. То же самое существо может сделать свободным действием сразу после действия «Выход из боя».</p>' },
  "Beta-3 Claws": { name: "Когти Беты-3" },
  "Its flesh can be butchered and sold for 1d10 solars to an appropriate vendor": { name: "Её тушу можно разделать и продать подходящему торговцу за 1d10 соляров" },
  "Elongated Bulk": { name: "Вытянутая туша", description: '<p>Когда Ацинади Гамма-7 совершает Натиск, его цель должна пройти <strong>среднюю (+0) проверку Рефлексов (Равновесие)</strong>, иначе будет сбита с ног.</p>' },
  "Wall Climber": { name: "Стенолаз", description: '<p>Ацинади Дельта-5 взбирается по большинству поверхностей без проверки. Атакуя сверху или защищаясь от цели внизу, он получает Преимущество.</p>' },
  "Its flesh can be butchered and sold for 5d10 solars to an appropriate vendor": { name: "Её тушу можно разделать и продать подходящему торговцу за 5d10 соляров" },
  "Gamma-7 Claws": { name: "Когти Гаммы-7" },
  "Home Turf": { name: "Своя территория", description: '<p>На территории своей банды огрин-гангер получает +1 к Решимости и Преимущество в проверках Дисциплины, Командования, Ориентирования и Скрытности.</p>' },
  "Ogryn Might": { name: "Огринская мощь", description: '<p>Огрин-гангер получает +10 к Силе и Выносливости, но −10 к Интеллекту и Товариществу.</p>' },
  "Ogryn Cleaver": { name: "Огринский тесак" },
  "Gang Colours": { name: "Цвета банды" },
  "2d10 solars": { name: "2d10 соляров" },
  "Voice of Authority": { name: "Властный голос", description: '<p>Лорд Фелпут всегда уверен в своей правоте — даже когда лжёт. Он получает +1 к Решимости и Преимущество в любой социальной проверке, кроме общения с персонажем более высокого общественного или имперского положения.</p>' },
  "500 solars": { name: "500 соляров" },
  "Harbinger's Faithful": { name: "Верный Предвестнику", description: '<p>Пока Предвестник в сознании и продолжает сражаться, культист Вертексис получает Преимущество в любых проверках Дисциплины (Страх), а его Решимость возрастает до 3. Если Предвестник падёт, Решимость культиста падает до 0 и тот обращается в бегство.</p>' },
  "Hand Scythe": { name: "Ручная коса" },
  "Icon of the Harbinger (A small carved skull))": { name: "Икона Предвестника (маленький резной череп)" },
  "8 solars": { name: "8 соляров" },
  "Left Hand of Sihn": { name: "Левая рука Сина", description: '<p>Корбид может действием приказать члену Двора Сина на средней дистанции немедленно совершить действие.</p>' },
  "Visions of Sihn": { name: "Видения Сина", description: '<p>Когда Корбид совершает действие <em>@UUID[Compendium.apex-imperialis.navis-core-journals.JournalEntry.6hX0E9XlPUoRaDaQ.JournalEntryPage.dZFX8HOdsFDpI7l0#resolve]{Берегитесь, господин!}</em>, чтобы защитить Маркиса Сина, она проходит <strong>лёгкую (+20) проверку Рефлексов (Уклонение)</strong>.</p>' },
  "Bureaucratic Boldness": { name: "Бюрократическая уверенность", description: '<p>Решимость надсмотрщика равна 3 при любом разговоре о документах, десятине и прочей бюрократии.</p>' },
  "Chief Whip": { name: "Главный надсмотрщик", description: '<p>Общаясь с членами Администратума, надсмотрщик может применять Командование (Запугивание) вместо Командования (Лидерство). Кроме того, он может действием приказать любому рядовому служащему Администратума немедленно совершить действие.</p>' },
  "several scrolls filled with records": { name: "Несколько свитков с записями" },
  "50 solars": { name: "50 соляров" },
  "Bestial Rage": { name: "Звериная ярость", description: '<p>Когда Талгор успешно атакует или получает рану, он получает +1 КУ к своей следующей атаке.</p>' },
  "Bullish Charge": { name: "Бычий натиск", description: '<p>Совершая Натиск, Талгор не получает Помеху в проверках Боя и Рефлексов.</p>' },
  "Malefic Psyker": { name: "Колдун-псайкер", description: '<p>Аркт Талгор владеет следующими малыми психосилами: «Призыв вредителей», «Аура ужаса» и «Психический удар».</p>' },
  "Bull Horns": { name: "Бычьи рога" },
  "Tattered Robes": { name: "Изодранные робы" },
  "Unholy Icon": { name: "Нечестивая икона" },
  "Incarceratus": { name: "Инкарцератус", description: '<p>Удерживая кого-либо в Захвате, вигил может свободным действием заковать его в оковы.</p>' },
  "Ambusher": { name: "Засадник" },
  "Cameleoline Training": { name: "Обучение работе с хамелеолином" },
  "Stalker's Riposte": { name: "Ответный удар ловчего" },
  "True Faith": { name: "Истинная вера" },
  "Burn the Witch": { name: "Сжечь ведьму" },
  "Candles": { name: "Свечи" },
  "Incense Burner": { name: "Кадильница" },
  "Sharpened Horns": { name: "Заострённые рога" },
  "Hoof Strike": { name: "Удар копытом" },
  "Makeshift Armour": { name: "Самодельная броня" },
  "Heldrax's Guardian": { name: "Страж Хелдракса" },
  "Mathematics": { name: "Математика" },
  "Heavily Augmented": { name: "Глубокая аугментация" },
  "Adeptus Mechanicus robes": { name: "Робы Адептус Механикус" },
  "300 solars": { name: "300 соляров" },
  "Stalwart": { name: "Стойкий" },
  "Echo Team Uniform": { name: "Форма группы «Эхо»" },
  "Herdcrafted Cleaver": { name: "Тесак стада" },
  "Tattered Rags": { name: "Изодранные лохмотья" },
  "Bio-Meltdown": { name: "Биораспад" },
  "Inhuman Physiology": { name: "Нечеловеческая физиология" },
  "Lightning Reflexes": { name: "Молниеносные рефлексы" },
  "Lethal Toxins": { name: "Смертоносные токсины" },
  "Overkill Protocols": { name: "Протоколы избыточного уничтожения" },
  "Sentinel Array": { name: "Сторожевой комплекс" },
  "Neuro-Gauntlet": { name: "Нейроперчатка" },
  "Executioner Pistol": { name: "Пистолет «Палач»" },
  "Hypertoxin Rounds": { name: "Гипертоксичные патроны" },
  "Mass Reactive Shells": { name: "Масс-реактивные снаряды" },
  "Industrial Tools": { name: "Промышленные инструменты" },
  "Ragged clothes": { name: "Рваная одежда" },
  "5 Solars": { name: "5 соляров" },
  "Shoddy Filtration Plugs": { name: "Дрянные фильтры-затычки" },
  "Delta-5 Claws": { name: "Когти Дельты-5" },
  "Its flesh can be butchered and sold for 3d10 solars to an appropriate vendor": { name: "Её тушу можно разделать и продать подходящему торговцу за 3d10 соляров" },
  "Guided Volley": { name: "Направленный залп" },
  "Grafted Muscle": { name: "Пересаженные мышцы" },
  "5 solars": { name: "5 соляров" },
  "Adeptus Mechanicus Robes": { name: "Робы Адептус Механикус" },
  "200 solars": { name: "200 соляров" },
  "Ragged Clothing": { name: "Рваная одежда" },
  "13 solars": { name: "13 соляров" },
  "Scuffed bottle of expensive amasec": { name: "Потёртая бутылка дорогого амасека" },
  "Unnatural Physique": { name: "Противоестественное телосложение" },
  "Mutant Claws": { name: "Когти мутанта" },
  "Locket containing a few strands of hair and a faded pict showing her former appearance": { name: "Медальон с несколькими прядями волос и выцветшим пиктом её прежнего облика" },
  "Cudgel": { name: "Дубинка" },
  "Candelabra": { name: "Канделябр" },
  "Censer": { name: "Кадило" },
  "Command Protocol": { name: "Командный протокол" },
  "Rad-saturation": { name: "Радиационное насыщение" },
  "Radium Carbine": { name: "Радиевый карабин" },
  "Skitarii raiments": { name: "Облачение скитария" },
  "Omnispex Augmetics": { name: "Аугметика омниспика" },
  "Infractionist Ruler": { name: "Вожак инфракционистов" },
  "Touch of Corruption": { name: "Прикосновение Порчи" },
  "Unrestrained Power": { name: "Необузданная сила" },
  "Heavy Flamer": { name: "Тяжёлый огнемёт" },
  "Heavy Flamer Butt (Improvised Weapon)": { name: "Приклад тяжёлого огнемёта (подручное оружие)" },
  "Not In My House": { name: "Не в моём доме" },
  "Augmetic Fist": { name: "Аугметический кулак" },
  "Argent Tongue": { name: "Серебряный язык" },
  "Light Leathers": { name: "Лёгкие кожи" },
  "an Auspex": { name: "Ауспик" },
  "1d10 x 100 solars": { name: "1d10 × 100 соляров" },
  "I'll Die Trying": { name: "Умру, но сделаю" },
  "Ragged Clothes": { name: "Рваная одежда" },
  "2 solars": { name: "2 соляра" },
  "Trained Operator": { name: "Обученный оператор" },
  "Data Disguiser": { name: "Сокрытие данных" },
  "Right Hand of Sihn": { name: "Правая рука Сина" },
  "Flaccid Fists": { name: "Дряблые кулаки" },
  "30 solars": { name: "30 соляров" },
  "Enhanced Data-tether": { name: "Улучшенная привязь данных" },
  "Aura of Discipline": { name: "Аура дисциплины" },
  "Summary Execution": { name: "Казнь на месте" },
  "a pair of dog tags": { name: "Пара армейских жетонов" }
};
