/**
 * The 93 talents, from the Talents chapter of the Russian edition
 * (стр. 102–117). The Russian book keeps the English alphabetical order of the
 * entries, which is what made the whole chapter readable against the pack list.
 *
 * Several of these names are compared as strings inside impmal's effect scripts
 * ("Blank" among them). They are safe to translate only because
 * module/script-names.js widens those comparisons — see that file first.
 *
 * Two deliberate departures from the page: "Вдохновляющие присутствие" is a
 * typo in the book and is written here in agreement, and the English pack name
 * "Faithful (imperial Cult)" keeps its lowercase i because that is how the
 * document is actually named and the build checks it.
 */

export const label = "Предметы (Основная книга)";

export const byName = {
  "Acute Sense": { type: "talent", name: "Обострённые чувства" },
  "Adrenaline Acceleration": { type: "talent", name: "Прилив адреналина" },
  "Agile Attacks": { type: "talent", name: "Проворные удары" },
  "Air of Authority": { type: "talent", name: "Аура власти" },
  Ambidextrous: { type: "talent", name: "Амбидекстрия" },
  "Applied Anatomy": { type: "talent", name: "Практическая анатомия" },
  Artistic: { type: "talent", name: "Человек искусства" },
  "Attentive Assistant": { type: "talent", name: "Заботливый помощник" },
  Blank: { type: "talent", name: "Пустой" },
  "Bone Breaker": { type: "talent", name: "Костолом" },
  Briber: { type: "talent", name: "Подкуп" },
  Bulwark: { type: "talent", name: "Щитоносец" },
  Burglar: { type: "talent", name: "Взломщик" },
  Chirurgeon: { type: "talent", name: "Хирургеон" },
  "Close Quarters Discipline": { type: "talent", name: "Огневая дисциплина" },
  "Combat Master": { type: "talent", name: "Мастер рукопашной" },
  "Condemn The Witch": { type: "talent", name: "Смерть ведьме!" },
  Contortionist: { type: "talent", name: "Человек-змея" },
  "Counter Attack": { type: "talent", name: "Контратака" },
  "Coup De Grâce": { type: "talent", name: "Последний удар" },
  "Data Delver": { type: "talent", name: "Инфоархеолог" },
  Deadeye: { type: "talent", name: "Орлиный глаз" },
  Dealmaker: { type: "talent", name: "Делец" },
  "Demolition Specialist": { type: "talent", name: "Сапёр" },
  "Devoted Servant": { type: "talent", name: "Честный труженик" },
  "Directed Strikes": { type: "talent", name: "Точные удары" },
  "Dirty Fighting": { type: "talent", name: "Грязный бой" },
  Disarm: { type: "talent", name: "Разоружение" },
  Distracting: { type: "talent", name: "Бесцеремонный" },
  "Disturbing Voice": { type: "talent", name: "Пугающий голос" },
  Drilled: { type: "talent", name: "Боевое слаживание" },
  "Dual Wielder": { type: "talent", name: "Парные клинки" },
  Duellist: { type: "talent", name: "Дуэлянт" },
  "Eidetic Memory": { type: "talent", name: "Идеальная память" },
  "Ever Vigilant": { type: "talent", name: "Всегда начеку" },
  "Exploit Vulnerability": { type: "talent", name: "Болевые точки" },
  "Extended Proprioception": { type: "talent", name: "Связь с машиной" },
  "Faithful (imperial Cult)": { type: "talent", name: "Набожность (Имперский культ)" },
  "False Retreat": { type: "talent", name: "Ложное отступление" },
  "Familiar Terrain": { type: "talent", name: "Я здесь как дома" },
  Fated: { type: "talent", name: "Избранник судьбы" },
  "Field Medicae": { type: "talent", name: "Полевой врачеватель" },
  Flagellant: { type: "talent", name: "Флагеллант" },
  "Flanking Fire": { type: "talent", name: "Фланкирующий огонь" },
  "Flesh Is Weak": { type: "talent", name: "Плоть слаба" },
  "Forbidden Knowledge": { type: "talent", name: "Запретные тайны" },
  Forger: { type: "talent", name: "Поддельные документы" },
  Frenzy: { type: "talent", name: "Неистовство" },
  "Full-auto Fanatic": { type: "talent", name: "Фанатичный обстрел" },
  "Gallows Humour": { type: "talent", name: "Висельный юмор" },
  "Gothic Gibberish": { type: "talent", name: "Готическая тарабарщина" },
  Guardian: { type: "talent", name: "Спаситель" },
  Gunslinger: { type: "talent", name: "Акимбо" },
  Hatred: { type: "talent", name: "Ненависть" },
  "Hit And Run": { type: "talent", name: "Ударил-отступил" },
  "Holdout Expert": { type: "talent", name: "Потайные карманы" },
  "Hypno-indoctrination": { type: "talent", name: "Гипнообучение" },
  "Icon Bearer": { type: "talent", name: "Икононосец" },
  "Ignorance Is My Shield": { type: "talent", name: "Неведение — щит мой" },
  Inheritor: { type: "talent", name: "Наследник" },
  "Inspiring Presence": { type: "talent", name: "Вдохновляющее присутствие" },
  Lawbringer: { type: "talent", name: "Слуга закона" },
  Lickspittle: { type: "talent", name: "Подхалим" },
  Martyrdom: { type: "talent", name: "Мученичество" },
  "Medicae Maverick": { type: "talent", name: "Медик-вольнодумец" },
  "Mental Fortress": { type: "talent", name: "Психическая крепость" },
  Mimic: { type: "talent", name: "Подражатель" },
  Overseer: { type: "talent", name: "Наставник" },
  Pathologist: { type: "talent", name: "Патологоанатом" },
  Phlebotomist: { type: "talent", name: "Кровопускатель" },
  Porter: { type: "talent", name: "Носильщик" },
  "Psychic Castigation": { type: "talent", name: "Психическое проклятие" },
  "Psychic Flood": { type: "talent", name: "Психический поток" },
  Psyker: { type: "talent", name: "Псайкер" },
  Quickdraw: { type: "talent", name: "Быстрое выхватывание" },
  "Rapid Reload": { type: "talent", name: "Быстрая перезарядка" },
  "Read Lips": { type: "talent", name: "Чтение по губам" },
  "Registered Trader": { type: "talent", name: "Зарегистрированный торговец" },
  "Sanctioned Psyker": { type: "talent", name: "Санкционированный псайкер" },
  "Secret Identity": { type: "talent", name: "Вторая личность" },
  "Shock Assault": { type: "talent", name: "Неожиданный удар" },
  Skulker: { type: "talent", name: "По пятам" },
  Slippery: { type: "talent", name: "Отскок" },
  "Superior Commander": { type: "talent", name: "Превосходный командир" },
  "Suppressing Fire": { type: "talent", name: "Огонь на подавление" },
  "Sure-footed": { type: "talent", name: "Незыблемый" },
  "Tactical Movement": { type: "talent", name: "Тактическое передвижение" },
  Tenacious: { type: "talent", name: "Живучий" },
  "Two-handed Cleave": { type: "talent", name: "Широкий замах" },
  "Unflinching Presence": { type: "talent", name: "Заразительная отвага" },
  Unremarkable: { type: "talent", name: "Непримечательный" },
  "Void Legs": { type: "talent", name: "Походка пустохода" },
  "Well-prepared": { type: "talent", name: "Хорошая подготовка" }
};
